services:
  api:
    build:
      dockerfile: .dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    ports:
      - 6379:6379
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
